const groups = {
  'Beans-Legumes': [
    'Baked Beans',
    'Beans',
    'Black Beans',
    'Chickpeas',
    'Green Beans',
    'Kidney Beans',
    'Lentils',
    'Lima Beans',
    'Pinto Beans',
    'Quinoa',
    'Refried Beans',
    'Tofu',
  ],
  Beverages: [
    'Alcohol',
    'Apple Juice',
    'Cappuccino',
    'Beer',
    'Chocolate Milk',
    'Cocktails',
    'Cocoa',
    'Coffee',
    'Juice',
    'Wine',
    'Tea',
    'Energy Drinks',
  ],
  'Breads-Cereals': [
    'Bagels',
    'Biscuits',
    'Bread',
    'Beer',
    'Breadsticks',
    'Buns',
    'Cereal',
    'Cornbread',
    'Croissants',
    'Muffins',
    'Muesli',
    'Oatmeal',
  ],
  'Cheese-Milk-Dairy': [
    'American Cheese',
    'Blue Cheese',
    'Butter',
    'Buttermilk',
    'Cheese',
    'Cream',
    'Half & Half',
    'Margarine',
    'Milk',
    'Mozzarella Cheese',
    'Yogurt',
    'Swiss Cheese',
  ],
  Eggs: [
    'Egg Whites',
    'Egg Yolks',
    'Eggs',
    'Fried Eggs',
    'Hard Boiled Eggs',
    'Omelets',
    'Poached Eggs',
    'Scrambled Eggs',
  ],
  'Fast-Food': [
    'Burgers',
    'Burritos',
    'Calzones',
    'Cheese Pizza',
    'Cheeseburgers',
    'Chicken Nuggets',
    'Curries',
    'Fajitas',
    'Hot Dogs',
    'Nachos',
    'Pizza',
    'Tacos',
  ],
  'Fish-Seafood': [
    'Anchovies',
    'Carp',
    'Crawfish',
    'Crab',
    'Eel',
    'Flounder',
    'Fish',
    'Lobster',
    'Mussels',
    'Octopus',
    'Salmon',
    'Shrimp',
  ],
  Fruit: [
    'Apples',
    'Apricots',
    'Bananas',
    'Blueberries',
    'Cherries',
    'Coconuts',
    'Dried Fruit',
    'Fruit Salad',
    'Kiwifruit',
    'Muffins',
    'Mangos',
    'Pears',
  ],
  Meat: [
    'Bacon',
    'Beef',
    'Bread',
    'Bologna',
    'Chicken',
    'Chicken Breast',
    'Duck',
    'Corned Beef',
    'Ground Beef',
    'Ham',
    'Pork',
    'Ribs',
  ],
  'Nuts-Seeds': [
    'Almonds',
    'Brazil Nuts',
    'Cashews',
    'Nuts',
    'Peanuts',
    'Pecans',
    'Pistachios',
    'Seeds',
    'Soy Nuts',
    'Walnuts',
    'Sunflower Seeds',
    'Macadamia Nuts',
  ],
  'Pasta-Rice-Noodles': [
    'Brown Rice',
    'Couscous',
    'Jambalaya',
    'Gnocchi',
    'Lasagna',
    'Macaroni',
    'Noodles',
    'Pasta',
    'Ravioli',
    'Risotto',
    'Tortellini',
    'Wild Rice',
  ],
  Salads: [
    'Caesar Salad',
    'Chicken Salad',
    'Coleslaw',
    'Egg Salad',
    'Garden Salad',
    'Greek Salad',
    'Pasta Salad',
    'Potato Salad',
    'Salads',
    'Taco Salad',
    'Tuna Salad',
  ],
  'Sauces-Spices-Spreads': [
    'Applesauce',
    'Barbecue Sauce',
    'Caesar Dressing',
    'Chutney',
    'Gravy',
    'Guacamole',
    'Dips',
    'Honey',
    'Jams',
    'Olive Oil',
    'Peanut Butter',
    'Salsa',
  ],
  Snacks: [
    'Cereal Bars',
    'Chips',
    'Corn Chips',
    'Gum',
    'Jerky',
    'Popcorn',
    'Potato Chips',
    'Pretzels',
    'Rice Cakes',
    'Sandwiches',
    'Sushi',
    'Tortilla Chips',
  ],
  Soups: [
    'Bisque',
    'Broth',
    'Chicken Soup',
    'Chili',
    'Gumbo',
    'Miso Soup',
    'Noodle Soup',
    'Soups',
    'Stews',
    'Tomato Soup',
  ],
  'Sweets-Candy-Desserts': [
    'Brownies',
    'Cakes',
    'Candies',
    'Chocolate',
    'Cheesecake',
    'Cookies',
    'Ice Cream Cones',
    'Fudge',
    'Ice Cream',
    'Ice Pop',
    'Pies',
    'Sorbet',
  ],
  Vegetables: [
    'Asparagus',
    'Baby Carrots',
    'Broccoli',
    'Cabbage',
    'Celery',
    'Tomatoes',
    'Corn',
    'Garlic',
    'Kale',
    'Lettuce',
    'Mushrooms',
    'Yam',
  ],
  Other: [
    'Desserts',
    'Dumplings',
    'Barley',
    'Chocolate',
    'Sherbet',
    'Fruit',
    'Bulgur',
    'Flour',
    'Porridge',
    'Fruit Cocktail',
    'Citrus Fruit',
    'Pome Fruit',
    'Stone Fruit',
    'Tropical Fruit',
    'Berries',
    'Melons',
    'Meat',
    'Eggs',
    'Chicken',
    'Grains',
    'Legumes',
    'Milk',
    'Yogurt',
    'Cheese',
    'Cakes',
    'Pastry',
    'Pies and Tarts',
    'Cookies',
    'Custards',
    'Prawns and Shrimp',
    'Tuna',
    'Salmon',
    'Nuts and Seeds',
    'Herbs and Spices',
    'Garnishes',
    'Oil',
    'Processed Foods',
  ],
};

export default groups;
