const groupsRecipes = {
  Diet: ['balanced', 'high-fiber', 'high-protein', 'low-carb', 'low-fat', 'low-sodium'],
  Health: [
    'alcohol-cocktail',
    'alcohol-free',
    'celery-free',
    'crustacean-free',
    'dairy-free',
    'egg-free',
    'fish-free',
    'gluten-free',
    'vegetarian',
    'pescatarian',
    'wheat-free',
    'peanut-free',
    'tree-nut-free',
    'soy-free',
    'shellfish-free',
    'pork-free',
    'red-meat-free',
    'mustard-free',
    'sesame-free',
    'lupine-free',
    'mollusk-free',
    'no-oil-added',
    'sulfite-free',
    'kosher',
    'immuno-supportive',
    'sugar-conscious',
    'vegan',
    'paleo',
    'low-sugar',
    'low-potassium',
    'kidney-friendly',
    'keto-friendly',
  ],
  MealType: ['Breakfast', 'Dinner', 'Lunch', 'Snack', 'Teatime'],
  DishType: [
    'Biscuits and cookies',
    'Bread',
    'Cereals',
    'Condiments and sauces',
    'Desserts',
    'Drinks',
    'Main course',
    'Pancake',
    'Preps',
    'Salad',
    'Sandwiches',
    'Soup',
    'Starter',
  ],
};
export default groupsRecipes;
