export const dataExerciseLight = [
  {
    id: 1,
    type: 'Light Activity',
    name: 'Sleeping',
    calsInHr: 65,
    image: 'https://i.ibb.co/f863XJL/sml-sleeping-gif.png',
  },
  {
    id: 2,
    type: 'Light Activity',
    name: 'Resting',
    calsInHr: 73,
    image: 'https://i.ibb.co/bv1b2N1/sml-resting.gif',
  },
  {
    id: 3,
    type: 'Light Activity',
    name: 'Desk Work',
    calsInHr: 109,
    image: 'https://i.ibb.co/hfXCXfg/sml-desk-work.gif',
  },
  {
    id: 4,
    type: 'Light Activity',
    name: 'Driving',
    calsInHr: 116,
    image: 'https://i.ibb.co/Y83MkSZ/sml-driving.gif',
  },
  {
    id: 5,
    type: 'Light Activity',
    name: 'Bathing',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 6,
    type: 'Light Activity',
    name: 'Singing',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 7,
    type: 'Light Activity',
    name: 'Spa',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 8,
    type: 'Light Activity',
    name: 'Showering',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 9,
    type: 'Light Activity',
    name: 'Sexual Activity',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 10,
    type: 'Light Activity',
    name: 'Sewing',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 11,
    type: 'Light Activity',
    name: 'Studying',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 12,
    type: 'Light Activity',
    name: 'Working',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 13,
    type: 'Light Activity',
    name: 'Music playing',
    calsInHr: 146,
    image: 'https://i.ibb.co/ydv4pLy/sml-music-playing.gif',
  },
  {
    id: 14,
    type: 'Light Activity',
    name: 'Reading',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 15,
    type: 'Light Activity',
    name: 'Karaoke',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 16,
    type: 'Light Activity',
    name: 'Golf',
    calsInHr: 146,
    image: 'https://i.ibb.co/HHwDpxp/sml-golf-cart.gif',
  },
  {
    id: 17,
    type: 'Light Activity',
    name: 'Walking (slow) - 2/mph',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 18,
    type: 'Light Activity',
    name: 'Cooking',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 19,
    type: 'Light Activity',
    name: 'Shopping',
    calsInHr: 167,
    image: 'https://i.ibb.co/Jqm6FzJ/sml-shopping.gif',
  },
  {
    id: 20,
    type: 'Light Activity',
    name: 'Housework',
    calsInHr: 182,
    image: 'https://i.ibb.co/7r0MrbY/sml-housework.gif',
  },
  {
    id: 21,
    type: 'Light Activity',
    name: 'Stretching (yoga)',
    calsInHr: 182,
    image: 'https://i.ibb.co/9GVgSPm/sml-stretching-yoga.gif',
  },
  {
    id: 22,
    type: 'Light Activity',
    name: 'Scooter',
    calsInHr: 218,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
];

export const dataExerciseModerate = [
  {
    id: 1,
    type: 'Moderate Activity',
    name: 'Vacuuming',
    calsInHr: 218,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 2,
    type: 'Moderate Activity',
    name: 'Cleaning',
    calsInHr: 218,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 3,
    type: 'Moderate Activity',
    name: 'Washing Car',
    calsInHr: 218,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 4,
    type: 'Moderate Activity',
    name: 'Boating or Canoeing',
    calsInHr: 218,
    image: 'https://i.ibb.co/d0YLJP9/sml-boating-or-canoeing.gif',
  },
  {
    id: 5,
    type: 'Moderate Activity',
    name: 'Sailing',
    calsInHr: 218,
    image: 'https://i.ibb.co/qdsvjL5/sml-sailing.gif',
  },
  {
    id: 6,
    type: 'Moderate Activity',
    name: 'Surfing',
    calsInHr: 218,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 7,
    type: 'Moderate Activity',
    name: 'Pilates',
    calsInHr: 226,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 8,
    type: 'Moderate Activity',
    name: 'Walking (moderate) - 3/mph',
    calsInHr: 240,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 9,
    type: 'Moderate Activity',
    name: 'Motor-Cross',
    calsInHr: 291,
    image: 'https://i.ibb.co/jbb9sdc/sml-motor-cross.gif',
  },
  {
    id: 10,
    type: 'Moderate Activity',
    name: 'Volleyball',
    calsInHr: 291,
    image: 'https://i.ibb.co/sKSnnL5/sml-volleyball.gif',
  },
  {
    id: 11,
    type: 'Moderate Activity',
    name: 'Baseball',
    calsInHr: 364,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 12,
    type: 'Moderate Activity',
    name: 'Archery',
    calsInHr: 146,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 13,
    type: 'Moderate Activity',
    name: 'Water Biking/Running',
    calsInHr: 291,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 14,
    type: 'Moderate Activity',
    name: 'Swimming (slow)',
    calsInHr: 291,
    image: 'https://i.ibb.co/NjsPt3r/sml-swimming-slow.gif',
  },
  {
    id: 15,
    type: 'Moderate Activity',
    name: 'Bowling',
    calsInHr: 291,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 16,
    type: 'Moderate Activity',
    name: 'Golf (moderate)',
    calsInHr: 291,
    image: 'https://i.ibb.co/HHwDpxp/sml-golf-cart.gif',
  },
  {
    id: 17,
    type: 'Moderate Activity',
    name: 'Walking (brisk) - 4/mph',
    calsInHr: 364,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 18,
    type: 'Moderate Activity',
    name: 'Dance (slow step)',
    calsInHr: 291,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 19,
    type: 'Moderate Activity',
    name: 'Hula Hoop',
    calsInHr: 364,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 20,
    type: 'Moderate Activity',
    name: 'Gym',
    calsInHr: 437,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 21,
    type: 'Moderate Activity',
    name: 'Netball',
    calsInHr: 437,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 22,
    type: 'Moderate Activity',
    name: 'Skiing (water)',
    calsInHr: 437,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
];

export const dataExerciseStrenuous = [
  {
    id: 1,
    type: 'Strenuous Activity',
    name: 'Zumba',
    calsInHr: 509,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 2,
    type: 'Strenuous Activity',
    name: 'Swimming (moderate)',
    calsInHr: 509,
    image: 'https://i.ibb.co/NjsPt3r/sml-swimming-slow.gif',
  },
  {
    id: 3,
    type: 'Strenuous Activity',
    name: 'Karate',
    calsInHr: 509,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 4,
    type: 'Strenuous Activity',
    name: 'Running - 7/mph',
    calsInHr: 837,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 5,
    type: 'Strenuous Activity',
    name: 'Body Balance',
    calsInHr: 509,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 6,
    type: 'Strenuous Activity',
    name: 'Power Jump',
    calsInHr: 509,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 7,
    type: 'Strenuous Activity',
    name: 'Aerobics',
    calsInHr: 533,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 8,
    type: 'Strenuous Activity',
    name: 'Fitness Training (Workout)',
    calsInHr: 509,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 9,
    type: 'Strenuous Activity',
    name: 'Crossfit',
    calsInHr: 509,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 10,
    type: 'Strenuous Activity',
    name: 'Weight Training (Bodybuilding)',
    calsInHr: 610,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 11,
    type: 'Strenuous Activity',
    name: 'Hockey',
    calsInHr: 582,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 12,
    type: 'Strenuous Activity',
    name: 'Cardio',
    calsInHr: 509,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 13,
    type: 'Strenuous Activity',
    name: 'Running - 10/mph',
    calsInHr: 1164,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 14,
    type: 'Strenuous Activity',
    name: 'Lacrosse',
    calsInHr: 582,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 15,
    type: 'Strenuous Activity',
    name: 'Football',
    calsInHr: 582,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 16,
    type: 'Strenuous Activity',
    name: 'Tennis',
    calsInHr: 582,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 17,
    type: 'Strenuous Activity',
    name: 'Snow Boarding',
    calsInHr: 509,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 18,
    type: 'Strenuous Activity',
    name: 'Soccer',
    calsInHr: 582,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 19,
    type: 'Strenuous Activity',
    name: 'Boxing',
    calsInHr: 873,
    image: 'https://i.ibb.co/YhF1Dtn/sml-boxing.gif',
  },
  {
    id: 20,
    type: 'Strenuous Activity',
    name: 'Air Climber',
    calsInHr: 582,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 21,
    type: 'Strenuous Activity',
    name: 'Skiing',
    calsInHr: 873,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
  {
    id: 22,
    type: 'Strenuous Activity',
    name: 'Endurance Sport',
    calsInHr: 582,
    image: 'https://i.ibb.co/C7f1c9j/sml-other.gif',
  },
];

export const allExerciseArray: DataExercise[] = dataExerciseLight
  .concat(dataExerciseModerate)
  .concat(dataExerciseStrenuous);

export interface DataExercise {
  id: number;
  type: string;
  name: string;
  calsInHr: number;
  image: string;
}
